unsigned long getfirstemptyblockpos(vhdd);
int metadata1(vhdd,int,int,int);
void setusedblock(vhdd,long int);
int name(vhdd*,char ***,int*,int*,int *,int *);
void bytetoint(char*,int*);
int createVHDD(unsigned long int fsize,unsigned long int bsize,vhdd *,char*);
void allocationTable(vhdd);
void puthardinfo(vhdd);
void setblockfree(vhdd,long int);
int metadatablockinitialize(vhdd);
int name1(vhdd,char ***,int *,int *,int *,int *);
int hextoint(unsigned char *);
void metafreeblock(vhdd,const char*,int);
void printblock(vhdd,int long,const char*,const char*);
int readblock(int,vhdd*);
int writeblock(int,vhdd);
void printbuff(vhdd);
unsigned long nameblockinitialize(vhdd);
int freeblocknm(vhdd,int);
int metadataallocationtable(vhdd*);
int stringsplit(char *,char ***,int);
void printnamesub(int,int,vhdd);
